name: NightVision
main: BeeAZZ\NightVision\Main
api: 4.0.0
version: 0.3
author: BeeAZZ
description: The Ability To See In The Dark

commands:
 vision:
  description: Turn on the ability to see in the dark
  permission: nightvision.command
permissions:
 nightvision.command:
  default: op
